---
- name: Install nfs-utils
  package:
    name: nfs-utils
    state: present

- name: Create mount directory
  file:
    path: "{{ nfs_client_mount_point }}"
    state: directory

- name: Mount NFS share
  mount:
    path: "{{ nfs_client_mount_point }}"
    src: "{{ hostvars['prdx-nfs101'].ansible_host }}:/var/nfs/shared"
    fstype: nfs
    opts: rw
    state: mounted

- name: Add to fstab
  mount:
    path: "{{ nfs_client_mount_point }}"
    src: "{{ hostvars['prdx-nfs101'].ansible_host }}:/var/nfs/shared"
    fstype: nfs
    opts: rw
    state: present
